remote_theme: Brian-boudrioux/workshops-jekyll-theme

titles_from_headings:
  enabled: false

defaults:
  - scope:
      path: ""
    values:
      layout: "default"

style: dev
title: Créer une API REST avec Express & MySQL  
description: "Projet fil rouge : Réseau social interne MyDigitalSchool"
show_clone: false
show_toc: true
lang: en
